### ISSUE TITLE
In Pick Module, with Prompt for qty turned on, cancelling out of "enter quantity" screen improperly decrements qty remaining to be picked

### ISSUE THREAD

**Issue by davidonelson** [DynEntTech/connectedwarehouse#3]
https://github.com/connectedbusiness/connectedwarehouse/issues/9

**Comment by Surinderkaur329** [comment]
Done.

**Comment by davidonelson** [comment]
problem is not fixed using "warehouse version 2.2.0 surinder kaur"

**Comment by davidonelson** [comment]
This issue was fixed (but may have caused new issues, opening separate issues for the new issues).
